[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if center.name == "Wee Joker" and (center.discovered or self.bypass_discovery_center) then"
position = "before"
payload = '''
if center.name == "Big Joker" then 
  H = H*1.5
  W = W*1.5
  self.T.h = H
  self.T.w = W
end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'elseif self.config.center.name == "Wee Joker" then '
position = "before"
payload = '''
elseif self.config.center.name == "Big Joker" then 
  self.T.h = H*scale*1.5*scale
  self.T.w = W*scale*1.5*scale
'''
match_indent = true
